### ISSUE TITLE
Implement default mobile topnav bar

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#247]
**Task Details**

The following issue is to serve as a tasklist of issues pertaining to our **default mobile topnav bar**

The flow of components for the same are as follows:
![Flow](https://user-images.githubusercontent.com/30471843/62251722-4748b580-b40e-11e9-9618-ee61df6f7628.png)

Prototype for menu interactions
<img src="https://user-images.githubusercontent.com/30471843/62296240-4e160d80-b48c-11e9-8382-56d8f97a73ab.gif" width="300" />

**Tasklist**
- [x] **Issue #248:** Implement main navigation bar (component marked as 0 consisting of 1, 5, 6 and 9)
- [ ] **Issue #249:** Implement hamburger menu (5 leads to 2, 3 and 4)
- [ ] **Issue #252:** Implement search (6 leads to 7 and 8)
- [x] **Issue #255:** Implement user menu (9 leads to 10)

**Comment by iisa** [comment]
@koderjoker closing as it has been merged.
