### ISSUE TITLE
Document props to all components

### ISSUE THREAD

**Issue by mitra42** [internetarchive/iaux#262]
**Task Details**

There are a number of components which take undocumented props, and what is worse in some cases (e.g. bookreader-wrapper-main) pass them on to other components or code so that it is almost impossible to figure out what they should be. 

**Verification**
I guess that noone finds Components with missing props

**Stakeholders**
@jbuckner @iisa

**Comment by mitra42** [comment]
Here is a list of components missing reasonable documentation - feel free to Edit or add new comments  ....
- sandbox
  - bookreader-component 
    - [ ] bookreader.js (unknown what component name for this)
    - [ ] bookreader-jsia.js BookReaderJsIa
    - [ ] bookreader-wrapper-main,jsx

**Comment by mhk19** [comment]
@mitra42  i want to solve this issue

**Comment by mitra42** [comment]
I'm not working on the IAUX code at all these days, so I think figuring out with @iisa or @jbuckner would be a good way to get involved.
