### ISSUE TITLE
Standarise search result cards to implement a uniform grid system for search results

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/iaux#38]
The following is the parent issue to track overall progress on designs of the search results tiles.

**Child issues for the same**
- [x] To decide on an equivalent height for all search result cards #195 
- [x] Change the information areas for borrow/waitlist/sensitive into image overlays #196
- [ ] Decide on an accessible colour palette

Individual issues for each type of card: #164 (media cards), #165 (account cards) and #166 (collection cards).

<hr>

**Issue description**
The following issue aims at making user navigation easier.

Due to non-uniform placement and varying sizes of search result cards in the search results, after the listing of 10-20 cards it becomes difficult to go through and distinguish between them.
![Screen Shot 2019-04-08 at 10 18 05 PM](https://user-images.githubusercontent.com/30471843/55757683-309edd00-5a72-11e9-8be9-4eb395d42e14.png)

The current search results require a uniform grid system. However, in order to implement so, we'd have to start standardizing our current `searchResultCard`s for collections, media and accounts.

**Comment by pezvi** [comment]
Thanks for documenting some of the specific issues. This one's also being worked on internally, so I'm tagging it as internal (though I'm leaving the issue open, so we can potentially follow up here).

**Comment by iisa** [comment]
This work will also help #33

**Comment by koderjoker** [comment]
Mockups for media cards
![Screen Shot 2019-06-06 at 10 00 43 PM](https://user-images.githubusercontent.com/30471843/59051297-251d3600-88aa-11e9-9871-4493ed585280.png)

Mockups for all cards (Media, collection, account and saved search)
![Screen Shot 2019-06-06 at 10 00 24 PM](https://user-images.githubusercontent.com/30471843/59051327-3ebe7d80-88aa-11e9-84e7-a7758dd125d2.png)

Sample composition of cards on user favourites page
![COmposition](https://user-images.githubusercontent.com/30471843/59051386-66154a80-88aa-11e9-9b0a-f1cdb16a272d.png)

**Comment by iisa** [comment]
@koderjoker @pezvi what is the status of this?
